### PR TITLE
Boilerplate

### PR DESCRIPTION
**Pull request by RobLoach**

### CODE REVIEW

**Comment by tunnckoCore** [comment]
:-1:

**Comment by TimothyGu** [comment]
@tunnckoCore care to explain why the -1?

**Comment by tunnckoCore** [comment]
Because force too many not needed things and dont like the style. I can only agree partially with the style of the readme.

**Comment by RobLoach** [comment]
I invite you to put up pull requests to [Boilerplate](https://github.com/jstransformers/boilerplate) and then those changes will be pulled downstream to all the transformers.

Style is simply syntax; As long as it's consistent, that's all that matters. The important thing is bringing Boilerplate in, so that's it's easily adaptable as Boilerplate evolves.

**Comment by RobLoach** [comment]
We should use https://github.com/jstransformers/boilerplate/wiki#update to update it without the history.

**Pull request closed without merging**
